source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'LwxFMDB_Example' do
  pod 'LwxFMDB', :path => '../'

  target 'LwxFMDB_Tests' do
    inherit! :search_paths

    
  end
end
